### ISSUE TITLE
Licensing Issues

### ISSUE THREAD

**Issue by Nich87** [ichbtrv/chatgpt-svelte#2]
I noticed that this repository does not currently contain the proper license. I am sorry that I have already forked it, but in the case of an unintended No license, could you please add the appropriate license?
If this is difficult, I will delete my forked repository as soon as possible.

Please fix this problem.
https://choosealicense.com/no-permission/

**Comment by ichbtrv** [comment]
Closed with https://github.com/ichbtrv/chatgpt-svelte/pull/6
